In [1]:
from pymongo import MongoClient
import pandas as pd
from datetime import datetime

In [2]:
client = MongoClient("mongodb://root:rootpass@localhost:27017")
print(client.server_info()['version'])

8.2.6

In [3]:
db = client['loja']
colecao = db['vendas']

In [4]:
dados = [
    {
        "cliente": "Ana",
        "produto": "Mouse",
        "categoria": "Informática",
        "quantidade": 2,
        "preco_unitario": 50,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 1),
        "forma_pagamento": "Cartão"
    },
    {
        "cliente": "Bruno",
        "produto": "Teclado",
        "categoria": "Informática",
        "quantidade": 1,
        "preco_unitario": 120,
        "cidade": "Jacarezinho",
        "data": datetime(2026, 3, 2),
        "forma_pagamento": "Pix"
    },
    {
        "cliente": "Carla",
        "produto": "Caderno",
        "categoria": "Papelaria",
        "quantidade": 5,
        "preco_unitario": 15,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 2),
        "forma_pagamento": "Dinheiro"
    },
    {
        "cliente": "Daniel",
        "produto": "Caneta",
        "categoria": "Papelaria",
        "quantidade": 10,
        "preco_unitario": 3,
        "cidade": "Salto Grande",
        "data": datetime(2026, 3, 3),
        "forma_pagamento": "Pix"
    },
    {
        "cliente": "Elaine",
        "produto": "Monitor",
        "categoria": "Informática",
        "quantidade": 1,
        "preco_unitario": 900,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 3),
        "forma_pagamento": "Cartão"
    },
    {
        "cliente": "Fabio",
        "produto": "Mochila",
        "categoria": "Acessórios",
        "quantidade": 2,
        "preco_unitario": 80,
        "cidade": "Jacarezinho",
        "data": datetime(2026, 3, 4),
        "forma_pagamento": "Boleto"
    },
    {
        "cliente": "Gabriela",
        "produto": "Livro",
        "categoria": "Livros",
        "quantidade": 3,
        "preco_unitario": 40,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 4),
        "forma_pagamento": "Pix"
    },
    {
        "cliente": "Henrique",
        "produto": "Fone",
        "categoria": "Informática",
        "quantidade": 2,
        "preco_unitario": 150,
        "cidade": "Assis",
        "data": datetime(2026, 3, 5),
        "forma_pagamento": "Cartão"
    },
    {
        "cliente": "Isabela",
        "produto": "Agenda",
        "categoria": "Papelaria",
        "quantidade": 4,
        "preco_unitario": 20,
        "cidade": "Salto Grande",
        "data": datetime(2026, 3, 5),
        "forma_pagamento": "Dinheiro"
    },
    {
        "cliente": "João",
        "produto": "Webcam",
        "categoria": "Informática",
        "quantidade": 1,
        "preco_unitario": 250,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 6),
        "forma_pagamento": "Pix"
    }
]

In [5]:
colecao.insert_many(dados)

InsertManyResult([ObjectId('69c3184fe91c861a966ad0ef'), ObjectId('69c3184fe91c861a966ad0f0'), ObjectId('69c3184fe91c861a966ad0f1'), ObjectId('69c3184fe91c861a966ad0f2'), ObjectId('69c3184fe91c861a966ad0f3'), ObjectId('69c3184fe91c861a966ad0f4'), ObjectId('69c3184fe91c861a966ad0f5'), ObjectId('69c3184fe91c861a966ad0f6'), ObjectId('69c3184fe91c861a966ad0f7'), ObjectId('69c3184fe91c861a966ad0f8')], acknowledged=True)

In [6]:
dado_exemplo = list(colecao.find({'cliente' : 'Bruno'}))
display(dado_exemplo)

[{'_id': ObjectId('69c3184fe91c861a966ad0f0'),
  'cliente': 'Bruno',
  'produto': 'Teclado',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 120,
  'cidade': 'Jacarezinho',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Pix'}]

In [8]:
dados_mongo = list(colecao.find({
    'preco_unitario' : {'$gte' : 100, '$lte' : 300}
}))

display(dados_mongo)

[{'_id': ObjectId('69c3184fe91c861a966ad0f0'),
  'cliente': 'Bruno',
  'produto': 'Teclado',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 120,
  'cidade': 'Jacarezinho',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3184fe91c861a966ad0f6'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3184fe91c861a966ad0f8'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'}]

In [9]:
dados_cidade = list(colecao.find({
    'cidade' : {'$in' : ['Ourinhos', 'Assis']}
}))

display(dados_cidade)

[{'_id': ObjectId('69c3184fe91c861a966ad0ef'),
  'cliente': 'Ana',
  'produto': 'Mouse',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 50,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3184fe91c861a966ad0f1'),
  'cliente': 'Carla',
  'produto': 'Caderno',
  'categoria': 'Papelaria',
  'quantidade': 5,
  'preco_unitario': 15,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3184fe91c861a966ad0f3'),
  'cliente': 'Elaine',
  'produto': 'Monitor',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 900,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3184fe91c861a966ad0f5'),
  'cliente': 'Gabriela',
  'produto': 'Livro',
  'categoria': 'Livros',
  'quantidade': 3,
  'preco_unitario': 40,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3184fe91c861a966ad0f6'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3184fe91c861a966ad0f8'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'}]

In [10]:
df = pd.DataFrame(dados_cidade)
df

,_id,cliente,produto,categoria,quantidade,preco_unitario,cidade,data,forma_pagamento
0,69c3184fe91c861a966ad0ef,Ana,Mouse,Informática,2,50,Ourinhos,2026-03-01,Cartão
1,69c3184fe91c861a966ad0f1,Carla,Caderno,Papelaria,5,15,Ourinhos,2026-03-02,Dinheiro
2,69c3184fe91c861a966ad0f3,Elaine,Monitor,Informática,1,900,Ourinhos,2026-03-03,Cartão
3,69c3184fe91c861a966ad0f5,Gabriela,Livro,Livros,3,40,Ourinhos,2026-03-04,Pix
4,69c3184fe91c861a966ad0f6,Henrique,Fone,Informática,2,150,Assis,2026-03-05,Cartão
5,69c3184fe91c861a966ad0f8,João,Webcam,Informática,1,250,Ourinhos,2026-03-06,Pix

In [11]:
df.isnull().sum()

_id                0
cliente            0
produto            0
categoria          0
quantidade         0
preco_unitario     0
cidade             0
data               0
forma_pagamento    0
dtype: int64

In [14]:
df['valor_total'] = df['quantidade'] * df['preco_unitario']
df.head(5)

,_id,cliente,produto,categoria,quantidade,preco_unitario,cidade,data,forma_pagamento,valor_total
0,69c3184fe91c861a966ad0ef,Ana,Mouse,Informática,2,50,Ourinhos,2026-03-01,Cartão,100
1,69c3184fe91c861a966ad0f1,Carla,Caderno,Papelaria,5,15,Ourinhos,2026-03-02,Dinheiro,75
2,69c3184fe91c861a966ad0f3,Elaine,Monitor,Informática,1,900,Ourinhos,2026-03-03,Cartão,900
3,69c3184fe91c861a966ad0f5,Gabriela,Livro,Livros,3,40,Ourinhos,2026-03-04,Pix,120
4,69c3184fe91c861a966ad0f6,Henrique,Fone,Informática,2,150,Assis,2026-03-05,Cartão,300

In [15]:
faturamento = df['valor_total'].sum()
print("Faturamento Total: ", faturamento)

Faturamento Total:  1745

In [16]:
faturamento_categoria = df.groupby('categoria')['valor_total'].sum().sort_values(ascending=False)
faturamento_categoria

categoria
Informática    1550
Livros          120
Papelaria        75
Name: valor_total, dtype: int64

In [17]:
faturamento_produto = df.groupby('produto')['valor_total'].sum().sort_values(ascending=False)
faturamento_produto

produto
Monitor    900
Fone       300
Webcam     250
Livro      120
Mouse      100
Caderno     75
Name: valor_total, dtype: int64

In [20]:
vendas_por_cidade = df['cidade'].value_counts()
vendas_por_cidade

cidade
Ourinhos    5
Assis       1
Name: count, dtype: int64

In [22]:
media_valor_vendas = df['valor_total'].mean()
print(f"Média do valor das vendas: {media_valor_vendas:.2f}")

Média do valor das vendas: 290.83

In [23]:
produto_top = df.groupby('produto')['valor_total'].sum().idxmax()
produto_top

'Monitor'

In [24]:
cidade_top = df['cidade'].value_counts().idxmax()
cidade_top

'Ourinhos'

In [25]:
relatorio = {
    'data_geracao' : datetime.now(),
    'faturamento_total' : float(faturamento),
    'faturamento_categoria' : faturamento_categoria.to_dict(),
    'produto_top' : produto_top,
    'cidade_top' : cidade_top
}

display(relatorio)

{'data_geracao': datetime.datetime(2026, 3, 25, 0, 36, 46, 186848),
 'faturamento_total': 1745.0,
 'faturamento_categoria': {'Informática': 1550,
  'Livros': 120,
  'Papelaria': 75},
 'produto_top': 'Monitor',
 'cidade_top': 'Ourinhos'}

In [26]:
colecao_relatorios = db['relatorios']
colecao_relatorios.insert_one(relatorio)

InsertOneResult(ObjectId('69c32e5fe91c861a966ad0f9'), acknowledged=True)

In [ ]:
for r in colecao_relatorios.find(): 
    display(r)

{'_id': ObjectId('69c32e5fe91c861a966ad0f9'),
 'data_geracao': datetime.datetime(2026, 3, 25, 0, 36, 46, 186000),
 'faturamento_total': 1745.0,
 'faturamento_categoria': {'Informática': 1550,
  'Livros': 120,
  'Papelaria': 75},
 'produto_top': 'Monitor',
 'cidade_top': 'Ourinhos'}